iterate

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -50,31 +50,37 @@ jobs:
       - name: Run basic tests and print logs
         run: |
           container_id=$(docker run -d -p 8888:8888 --security-opt seccomp=unconfined -e JUPYTER_TOKEN=secret jupyter-remote-desktop-proxy)
-          sleep 5
+          sleep 3
+          TEST_OK=true
 
-          echo "Testing /desktop/ to return rendered index.html template"
-          curl --silent --fail 'http://localhost:8888/desktop/?token=secret' | grep 'Jupyter Remote Desktop Proxy' && echo "Pass" || { echo "Fail" && TEST_OK=false }
+          echo "::group::Testing /desktop/ to return rendered index.html template"
+          curl --silent --fail 'http://localhost:8888/desktop/?token=secret' | grep --quiet 'Jupyter Remote Desktop Proxy' && echo "Passed" || { echo "Failed" && TEST_OK=false; }
+          echo "::endgroup::"
 
-          echo "Testing /desktop/ to provide pre-built viewer.js"
-          curl --silent --fail 'http://localhost:8888/desktop/static/dist/viewer.js?token=secret' > /dev/null && echo "Pass" || { echo "Fail" && TEST_OK=false }
+          echo "::group::Testing /desktop/ to provide pre-built viewer.js"
+          curl --silent --fail 'http://localhost:8888/desktop/static/dist/viewer.js?token=secret' > /dev/null && echo "Passed" || { echo "Failed" && TEST_OK=false; }
+          echo "::endgroup::"
 
-          echo "Testing /desktop-websockify/ to return a vncserver typical response twice..."
-          websocat --binary --one-message --exit-on-eof 'ws://127.0.0.1:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Pass" || { echo "Fail" && TEST_OK=false }
+          echo "::group::Testing /desktop-websockify/ to return a vncserver typical response, accepting one initial test failure"
+          websocat --binary --one-message --exit-on-eof 'ws://127.0.0.1:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Passed initial websocket test" || \
+          { echo "Failed initial websocket test" && sleep 3 && websocat --binary --one-message --exit-on-eof 'ws://127.0.0.1:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Pass second websocket test" || { echo "Failed second websocket test" && TEST_OK=false; } }
+          echo "::endgroup::"
 
           echo "::group::jupyter_server logs"
           docker logs $container_id
-          echo ::endgroup::
+          echo "::endgroup::"
 
           echo "::group::vncserver logs"
           docker exec $container_id bash -c "cat ~/.vnc/*.log"
-          echo ::endgroup::
+          echo "::endgroup::"
+
+          echo "::group::Testing container's ability to terminate via SIGTERM"
+          timeout 5 docker stop $container_id > /dev/null && echo "Passed" || { echo "Failed" && TEST_OK=false; }
+          echo "::endgroup::"
 
           if [ "$TEST_OK" == "false" ]; then
-            echo "One or more tests failed!"
-            echo "::group::another websocat connect attempt with --verbose"
-            websocat --binary --one-message --exit-on-eof --verbose 'ws://127.0.0.1:8888/desktop-websockify/?token=secret'
-            echo ::endgroup::
-            exit 1
+              echo "One or more tests failed!"
+              exit 1
           fi
 
       # TODO: Check VNC desktop works, e.g. by comparing Playwright screenshots
