back to --one-message flag

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -63,9 +63,9 @@ jobs:
           echo "::endgroup::"
 
           echo "::group::Testing /desktop-websockify/ to return a vncserver typical response, accepting one initial test failure"
-          websocat --no-async-stdio --binary --max-messages=1 --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Passed initial websocket test" || { \
-            echo "Failed initial websocket test" && sleep 3 && websocat -vv --no-async-stdio --binary --max-messages=1 --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | tee /dev/tty | grep --quiet RFB && echo "Pass second websocket test" || { \
-              echo "Failed second websocket test" && sleep 3 && websocat --no-async-stdio --binary --max-messages=1 --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Pass second websocket test" || { echo "Failed third websocket test" && TEST_OK=false; } \
+          websocat --no-async-stdio --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Passed initial websocket test" || { \
+            echo "Failed initial websocket test" && sleep 3 && websocat -vv --no-async-stdio --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | tee /dev/tty | grep --quiet RFB && echo "Pass second websocket test" || { \
+              echo "Failed second websocket test" && sleep 3 && websocat --no-async-stdio --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Pass second websocket test" || { echo "Failed third websocket test" && TEST_OK=false; } \
             } \
           }
           echo "::endgroup::"
