Reduce to just outside container tests

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -82,32 +82,16 @@ jobs:
         if: always()
         run: |
           container_id=$(docker run -d -p 5901:5901 ${{ matrix.image }} vncserver -xstartup /opt/install/jupyter_remote_desktop_proxy/share/xstartup -verbose -fg -geometry 1680x1050 -SecurityTypes None -rfbport 5901)
+          sleep 1
 
-          echo "::group::Installing netcat (inside container)"
-          docker exec --user root $container_id bash -c '
-            apt update
-            apt install -y netcat
-          '
-          echo "::endgroup::"
-
-          echo "::group::Testing vncserver with netcat (inside container)"
-          docker exec -it $container_id bash -c 'timeout --preserve-status 1 nc -v localhost 5901' 2>&1 | tee output-inside.txt
-          cat output-inside.txt  | grep --quiet RFB && echo "Passed inside test"  || { echo "Failed inside test" && TEST_OK=false; }
-          echo "::endgroup::"
-
-          echo "::group::Testing vncserver with netcat (outside container)"
-          timeout --preserve-status 1 nc -v localhost 5901 2>&1 | tee output-outside.txt
-          cat output-outside.txt | grep --quiet RFB && echo "Passed outside test" || { echo "Failed outside test" && TEST_OK=false; }
+          echo "::group::Testing vncserver with netcat"
+          timeout --preserve-status 1 nc -v localhost 5901 2>&1 | tee output.txt
+          cat output.txt | grep --quiet RFB && echo "Passed test" || { echo "Failed test" && TEST_OK=false; }
           echo "::endgroup::"
 
           echo "::group::vncserver logs"
           docker exec $container_id bash -c "cat ~/.vnc/*.log"
           echo "::endgroup::"
-
-          echo "netstat inside container"
-          docker exec $container_id netstat -na --tcp | grep -E "(:5901|:5902)"
-          echo "netstat outside container"
-          netstat -na --tcp | grep -E "(:5901|:5902)"
 
           docker stop $container_id > /dev/null
           if [ "$TEST_OK" == "false" ]; then
@@ -121,22 +105,9 @@ jobs:
           container_id=$(docker run -d -p 5901:5901 ${{ matrix.image }} websockify --verbose --log-file=/tmp/websockify.log --heartbeat=30 5901 -- vncserver -xstartup /opt/install/jupyter_remote_desktop_proxy/share/xstartup -verbose -fg -geometry 1680x1050 -SecurityTypes None -rfbport 5901)
           sleep 3
 
-          echo "::group::Installing websocat (inside container)"
-          docker exec --user root $container_id bash -c '
-            wget -q https://github.com/vi/websocat/releases/download/v1.12.0/websocat.x86_64-unknown-linux-musl \
-              -O /usr/local/bin/websocat
-            chmod +x /usr/local/bin/websocat
-          '
-          echo "::endgroup::"
-
-          echo "::group::Testing websockify'ed vncserver with websocat (inside container)"
-          docker exec -it $container_id bash -c 'websocat --binary --one-message --exit-on-eof "ws://localhost:5901/"' 2>&1 | tee output-inside.txt
-          cat output-inside.txt  | grep --quiet RFB && echo "Passed inside test"  || { echo "Failed inside test" && TEST_OK=false; }
-          echo "::endgroup::"
-
-          echo "::group::Testing websockify'ed vncserver with websocat (outside container)"
-          websocat --binary --one-message --exit-on-eof "ws://localhost:5901/" 2>&1 | tee output-outside.txt
-          cat output-outside.txt | grep --quiet RFB && echo "Passed outside test" || { echo "Failed outside test" && TEST_OK=false; }
+          echo "::group::Testing websockify'ed vncserver with websocat"
+          websocat --binary --one-message --exit-on-eof "ws://localhost:5901/" 2>&1 | tee output.txt
+          cat output.txt | grep --quiet RFB && echo "Passed test" || { echo "Failed test" && TEST_OK=false; }
           echo "::endgroup::"
 
           echo "::group::websockify logs"
@@ -168,9 +139,10 @@ jobs:
           echo "::endgroup::"
 
           echo "::group::Testing /desktop-websockify/ to return a vncserver typical response, accepting one initial test failure"
-          websocat --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Passed initial websocket test" || { \
-            echo "Failed initial websocket test" && sleep 3 && websocat --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | tee /dev/tty | grep --quiet RFB && echo "Passed second websocket test" || { echo "Failed second websocket test" && TEST_OK=false; } \
-          }
+          websocat --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | \
+              grep --quiet RFB && echo "Passed initial websocket test" || { \
+                  echo "Failed initial websocket test" && sleep 3 && websocat --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Passed second websocket test" || { echo "Failed second websocket test" && TEST_OK=false; } \
+              }
           echo "::endgroup::"
 
           echo "::group::jupyter_server logs"
