Try a third time...

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -62,8 +62,11 @@ jobs:
           echo "::endgroup::"
 
           echo "::group::Testing /desktop-websockify/ to return a vncserver typical response, accepting one initial test failure"
-          websocat --binary --one-message --exit-on-eof 'ws://127.0.0.1:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Passed initial websocket test" || \
-          { echo "Failed initial websocket test" && sleep 3 && websocat --binary --one-message --exit-on-eof 'ws://127.0.0.1:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Pass second websocket test" || { echo "Failed second websocket test" && TEST_OK=false; } }
+          websocat --binary --one-message --exit-on-eof 'ws://127.0.0.1:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Passed initial websocket test" || { \
+            echo "Failed initial websocket test" && sleep 3 && websocat --binary --one-message --exit-on-eof 'ws://127.0.0.1:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Pass second websocket test" || { \
+              echo "Failed second websocket test" && sleep 3 && websocat --binary --one-message --exit-on-eof 'ws://127.0.0.1:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Pass second websocket test" || { echo "Failed third websocket test" && TEST_OK=false; } \
+            } \
+          }
           echo "::endgroup::"
 
           echo "::group::jupyter_server logs"
