cleanup

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -84,7 +84,7 @@ jobs:
           docker stop $container_id > /dev/null
           cat output.txt | grep --quiet RFB
 
-      - name: Run basic tests and print logs
+      - name: Test jupyter-server-proxy starting and proxying to websockify'ed vncserver with websocat
         run: |
           container_id=$(docker run -d -p 8888:8888 --security-opt seccomp=unconfined -e JUPYTER_TOKEN=secret jupyter-remote-desktop-proxy)
           sleep 3
@@ -100,37 +100,20 @@ jobs:
 
           echo "::group::Testing /desktop-websockify/ to return a vncserver typical response, accepting one initial test failure"
           websocat --no-async-stdio --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Passed initial websocket test" || { \
-            echo "Failed initial websocket test" && sleep 3 && websocat -vv --no-async-stdio --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | tee /dev/tty | grep --quiet RFB && echo "Pass second websocket test" || { \
-              echo "Failed second websocket test" && sleep 3 && websocat --no-async-stdio --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Pass second websocket test" || { echo "Failed third websocket test" && TEST_OK=false; } \
-            } \
+            echo "Failed initial websocket test" && sleep 3 && websocat -vv --no-async-stdio --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | tee /dev/tty | grep --quiet RFB && echo "Pass second websocket test" || { echo "Failed second websocket test" && TEST_OK=false; } \
           }
-          echo "::endgroup::"
-
-          echo "::group::Installing websocat in container"
-          docker exec --user root $container_id bash -c '
-            wget -q https://github.com/vi/websocat/releases/download/v1.12.0/websocat.x86_64-unknown-linux-musl \
-              -O /usr/local/bin/websocat
-            chmod +x /usr/local/bin/websocat
-            websocat --help=long
-          '
-          echo "::endgroup::"
-
-          echo "::group::Testing /desktop-websockify/ to return a vncserver typical response from within the container"
-          docker exec $container_id bash -c '
-            websocat -vv --no-async-stdio --binary --one-message --exit-on-eof 'ws://localhost:5901'
-          '
           echo "::endgroup::"
 
           echo "::group::jupyter_server logs"
           docker logs $container_id
           echo "::endgroup::"
 
-          echo "::group::vncserver logs"
-          docker exec $container_id bash -c "cat ~/.vnc/*.log"
-          echo "::endgroup::"
-
           echo "::group::websockify logs"
           docker exec $container_id bash -c "cat /tmp/websockify-*.log"
+          echo "::endgroup::"
+
+          echo "::group::vncserver logs"
+          docker exec $container_id bash -c "cat ~/.vnc/*.log"
           echo "::endgroup::"
 
           echo "::group::Testing container's ability to terminate via SIGTERM"
