blurb-of-testing

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -13,6 +13,47 @@ on:
   workflow_dispatch:
 
 jobs:
+  dummy:
+    runs-on: ubuntu-22.04
+    steps:
+      - name: "1"
+        run: |
+          # container_id=$(docker run -d -p 5901:5901 --security-opt seccomp=unconfined quay.io/consideratio/test:turbo vncserver -xstartup /opt/install/jupyter_remote_desktop_proxy/share/xstartup -verbose -fg -geometry 1680x1050 -SecurityTypes None -rfbport 5901)
+          container_id=$(docker run -d -p 5901:5901 -v $(pwd):/mnt/test --security-opt seccomp=unconfined quay.io/consideratio/test:turbo python /mnt/test/dummy-tcp-server.py)
+          sleep 3
+
+          # echo "::group::Installing netcat (inside container)"
+          # docker exec --user root $container_id bash -c '
+          #   apt update
+          #   apt install -y netcat
+          # '
+          # echo "::endgroup::"
+
+          echo "::group::Testing vncserver with netcat (inside container)"
+          docker exec $container_id bash -c 'timeout --preserve-status 1 nc -v localhost 5901' 2>&1 | tee output-inside.txt
+          cat output-inside.txt  | grep --quiet RFB && echo "Passed inside test"  || { echo "Failed inside test" && TEST_OK=false; }
+          echo "::endgroup::"
+
+          echo "::group::Testing vncserver with netcat (outside container)"
+          timeout --preserve-status 1 nc -v localhost 5901 2>&1 | tee output-outside.txt
+          cat output-outside.txt | grep --quiet RFB && echo "Passed outside test" || { echo "Failed outside test" && TEST_OK=false; }
+          echo "::endgroup::"
+
+          # echo "::group::vncserver logs"
+          # docker exec $container_id bash -c "cat ~/.vnc/*.log"
+          # echo "::endgroup::"
+
+          docker logs $container_id
+          docker stop $container_id > /dev/null
+          if [ "$TEST_OK" == "false" ]; then
+              echo "One or more tests failed!"
+              exit 1
+          fi
+      # - name: 2
+      #   run: |
+
+
+
   container:
     runs-on: ubuntu-22.04
     timeout-minutes: 10
@@ -64,7 +105,7 @@ jobs:
         if: always()
         run: |
           container_id=$(docker run -d -p 5901:5901 --security-opt seccomp=unconfined ${{ matrix.image }} vncserver -xstartup /opt/install/jupyter_remote_desktop_proxy/share/xstartup -verbose -fg -geometry 1680x1050 -SecurityTypes None -rfbport 5901)
-          sleep 5
+          sleep 1
 
           # echo "::group::Installing netcat (inside container)"
           # docker exec --user root $container_id bash -c '
@@ -108,12 +149,12 @@ jobs:
           # echo "::endgroup::"
 
           echo "::group::Testing websockify'ed vncserver with websocat (inside container)"
-          docker exec $container_id bash -c 'websocat -vv --no-async-stdio --binary --one-message --exit-on-eof "ws://localhost:5901/"' 2>&1 | tee output-inside.txt
+          docker exec $container_id bash -c 'websocat --binary --one-message --exit-on-eof "ws://localhost:5901/"' 2>&1 | tee output-inside.txt
           cat output-inside.txt  | grep --quiet RFB && echo "Passed inside test"  || { echo "Failed inside test" && TEST_OK=false; }
           echo "::endgroup::"
 
           echo "::group::Testing websockify'ed vncserver with websocat (outside container)"
-          websocat -vv --no-async-stdio --binary --one-message --exit-on-eof "ws://localhost:5901/" 2>&1 | tee output-outside.txt
+          websocat --binary --one-message --exit-on-eof "ws://localhost:5901/" 2>&1 | tee output-outside.txt
           cat output-outside.txt | grep --quiet RFB && echo "Passed outside test" || { echo "Failed outside test" && TEST_OK=false; }
           echo "::endgroup::"
 
@@ -146,8 +187,8 @@ jobs:
           echo "::endgroup::"
 
           echo "::group::Testing /desktop-websockify/ to return a vncserver typical response, accepting one initial test failure"
-          websocat --no-async-stdio --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Passed initial websocket test" || { \
-            echo "Failed initial websocket test" && sleep 3 && websocat -vv --no-async-stdio --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | tee /dev/tty | grep --quiet RFB && echo "Passed second websocket test" || { echo "Failed second websocket test" && TEST_OK=false; } \
+          websocat --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Passed initial websocket test" || { \
+            echo "Failed initial websocket test" && sleep 3 && websocat --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | tee /dev/tty | grep --quiet RFB && echo "Passed second websocket test" || { echo "Failed second websocket test" && TEST_OK=false; } \
           }
           echo "::endgroup::"
 
