panic

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -48,19 +48,45 @@ jobs:
           # to this, we fallback to use the errorcode of vncsrever -list.
           docker run jupyter-remote-desktop-proxy bash -c "vncserver -help || vncserver -list > /dev/null"
 
-      - name: Test vncserver with netcat (in container)
+      - name: Test vncserver with netcat (inside container)
         run: |
           container_id=$(docker run -d --security-opt seccomp=unconfined jupyter-remote-desktop-proxy vncserver -xstartup /opt/install/jupyter_remote_desktop_proxy/share/xstartup -verbose -localhost -fg -geometry 1680x1050 -SecurityTypes None)
 
-          echo "::group::Installing netcat (in container)"
+          echo "::group::Installing netcat (inside container)"
           docker exec --user root $container_id bash -c '
             apt update
             apt install -y netcat
           '
           echo "::endgroup::"
 
-          echo "::group::Testing vncserver with netcat (in container)"
-          docker exec $container_id bash -c 'nc -w 1 localhost 5901 2>&1' | tee -a output.txt
+          echo "::group::Testing vncserver with netcat (inside container)"
+          docker exec $container_id bash -c 'nc -w 1 localhost 5901 2>&1' | tee output.txt
+          echo "::endgroup::"
+
+          echo "::group::vncserver logs"
+          docker exec $container_id bash -c "cat ~/.vnc/*.log"
+          echo "::endgroup::"
+
+          docker stop $container_id > /dev/null
+          cat output.txt | grep --quiet RFB
+
+      - name: Test websockify'ed vncserver with websocat (inside container)
+        run: |
+          container_id=$(docker run -d --security-opt seccomp=unconfined jupyter-remote-desktop-proxy websockify --verbose --log-file=/tmp/websockify.log --heartbeat=30 5901 -- vncserver -xstartup /opt/install/jupyter_remote_desktop_proxy/share/xstartup -verbose -fg -geometry 1680x1050 -SecurityTypes None -rfbport 5902)
+          echo "::group::Installing websocat (inside container)"
+          docker exec --user root $container_id bash -c '
+            wget -q https://github.com/vi/websocat/releases/download/v1.12.0/websocat.x86_64-unknown-linux-musl \
+              -O /usr/local/bin/websocat
+            chmod +x /usr/local/bin/websocat
+          '
+          echo "::endgroup::"
+
+          echo "::group::Testing websockify'ed vncserver with websocat (inside container)"
+          docker exec $container_id bash -c 'websocat -vv --no-async-stdio --binary --one-message --exit-on-eof "ws://localhost:5901/"' 2>&1 | tee output.txt
+          echo "::endgroup::"
+
+          echo "::group::websockify logs"
+          docker exec $container_id bash -c "cat /tmp/websockify.log"
           echo "::endgroup::"
 
           echo "::group::vncserver logs"
@@ -72,11 +98,11 @@ jobs:
 
       - name: Test vncserver with netcat (outside container)
         run: |
-          container_id=$(docker run -d -p 5901:5901 --security-opt seccomp=unconfined jupyter-remote-desktop-proxy vncserver -xstartup /opt/install/jupyter_remote_desktop_proxy/share/xstartup -verbose -localhost -fg -geometry 1680x1050 -SecurityTypes None)
+          container_id=$(docker run -d -p 5901:5901 --security-opt seccomp=unconfined jupyter-remote-desktop-proxy vncserver -xstartup /opt/install/jupyter_remote_desktop_proxy/share/xstartup -verbose -fg -geometry 1680x1050 -SecurityTypes None -rfbport 5902)
           sleep 3
 
           echo "::group::Testing vncserver with netcat (outside container)"
-          nc -w 1 localhost 5901 2>&1 | tee -a output.txt
+          nc -v -w1 localhost 5901 2>&1 | tee output.txt
           echo "::endgroup::"
 
           echo "::group::vncserver logs"
@@ -92,7 +118,7 @@ jobs:
           sleep 3
 
           echo "::group::Testing websockify'ed vncserver with websocat (outside container)"
-          websocat -v --no-async-stdio --binary --one-message --exit-on-eof 'ws://localhost:5901/' 2>&1 | tee -a output.txt
+          websocat -v --no-async-stdio --binary --one-message --exit-on-eof 'ws://localhost:5901/' 2>&1 | tee output.txt
           echo "::endgroup::"
 
           echo "::group::websockify logs"
@@ -122,7 +148,7 @@ jobs:
 
           echo "::group::Testing /desktop-websockify/ to return a vncserver typical response, accepting one initial test failure"
           websocat --no-async-stdio --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | grep --quiet RFB && echo "Passed initial websocket test" || { \
-            echo "Failed initial websocket test" && sleep 3 && websocat -vv --no-async-stdio --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | tee /dev/tty | grep --quiet RFB && echo "Pass second websocket test" || { echo "Failed second websocket test" && TEST_OK=false; } \
+            echo "Failed initial websocket test" && sleep 3 && websocat -vv --no-async-stdio --binary --one-message --exit-on-eof 'ws://localhost:8888/desktop-websockify/?token=secret' | tee /dev/tty | grep --quiet RFB && echo "Passed second websocket test" || { echo "Failed second websocket test" && TEST_OK=false; } \
           }
           echo "::endgroup::"
 
@@ -144,8 +170,8 @@ jobs:
 
           if [ "$TEST_OK" == "false" ]; then
               echo "One or more tests failed!"
-              exit 1
           fi
+              exit 1
 
       # TODO: Check VNC desktop works, e.g. by comparing Playwright screenshots
       # https://playwright.dev/docs/test-snapshots
